---

- hosts: managed_servers
  strategy: free
  vars:
    favcolor: blue
  vars_files:
    - /home/aganashcse/ansible-weblogic-osb-cluster-installation/inventory/prod/osb/group_vars/all.yml

  roles:
    - { role: /home/aganashcse/ansible-weblogic-osb-cluster-installation/roles/java, tags: 'install' }




